/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param role The role of the author of this message.
 * @param content The contents of the message
 */

data class ChatCompletionResponseMessage (
    /* The role of the author of this message. */
    @Json(name = "role")
    val role: ChatCompletionResponseMessage.Role,
    /* The contents of the message */
    @Json(name = "content")
    val content: kotlin.String
) {

    /**
     * The role of the author of this message.
     * Values: system,user,assistant
     */
    enum class Role(val value: kotlin.String) {
        @Json(name = "system") system("system"),
        @Json(name = "user") user("user"),
        @Json(name = "assistant") assistant("assistant");
    }
}

