/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param query Query to search against the documents.
 * @param documents Up to 200 documents to search over, provided as a list of strings.  The maximum document length (in tokens) is 2034 minus the number of tokens in the query.  You should specify either `documents` or a `file`, but not both. 
 * @param file The ID of an uploaded file that contains documents to search over.  You should specify either `documents` or a `file`, but not both. 
 * @param maxRerank The maximum number of documents to be re-ranked and returned by search.  This flag only takes effect when `file` is set. 
 * @param returnMetadata A special boolean flag for showing metadata. If set to `true`, each document entry in the returned JSON will contain a \"metadata\" field.  This flag only takes effect when `file` is set. 
 */

data class CreateSearchRequest (
    /* Query to search against the documents. */
    @Json(name = "query")
    val query: kotlin.String,
    /* Up to 200 documents to search over, provided as a list of strings.  The maximum document length (in tokens) is 2034 minus the number of tokens in the query.  You should specify either `documents` or a `file`, but not both.  */
    @Json(name = "documents")
    val documents: kotlin.collections.List<kotlin.String>? = null,
    /* The ID of an uploaded file that contains documents to search over.  You should specify either `documents` or a `file`, but not both.  */
    @Json(name = "file")
    val file: kotlin.String? = null,
    /* The maximum number of documents to be re-ranked and returned by search.  This flag only takes effect when `file` is set.  */
    @Json(name = "max_rerank")
    val maxRerank: kotlin.Int? = null,
    /* A special boolean flag for showing metadata. If set to `true`, each document entry in the returned JSON will contain a \"metadata\" field.  This flag only takes effect when `file` is set.  */
    @Json(name = "return_metadata")
    val returnMetadata: kotlin.Boolean? = null
)

