/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param tokens 
 * @param tokenLogprobs 
 * @param topLogprobs 
 * @param textOffset 
 */

data class CreateCompletionResponseLogprobs (
    @Json(name = "tokens")
    val tokens: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "token_logprobs")
    val tokenLogprobs: kotlin.collections.List<java.math.BigDecimal>? = null,
    @Json(name = "top_logprobs")
    val topLogprobs: kotlin.collections.List<kotlin.Any>? = null,
    @Json(name = "text_offset")
    val textOffset: kotlin.collections.List<kotlin.Int>? = null
)

