/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.CreateAnswerResponseSelectedDocuments

import com.squareup.moshi.Json

/**
 * 
 * @param `object` 
 * @param model 
 * @param searchModel 
 * @param completion 
 * @param answers 
 * @param selectedDocuments 
 */

data class CreateAnswerResponse (
    @Json(name = "object")
    val `object`: kotlin.String? = null,
    @Json(name = "model")
    val model: kotlin.String? = null,
    @Json(name = "search_model")
    val searchModel: kotlin.String? = null,
    @Json(name = "completion")
    val completion: kotlin.String? = null,
    @Json(name = "answers")
    val answers: kotlin.collections.List<kotlin.String>? = null,
    @Json(name = "selected_documents")
    val selectedDocuments: kotlin.collections.List<CreateAnswerResponseSelectedDocuments>? = null
)

