/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param promptTokens 
 * @param totalTokens 
 */

data class CreateEmbeddingResponseUsage (
    @Json(name = "prompt_tokens")
    val promptTokens: kotlin.Int,
    @Json(name = "total_tokens")
    val totalTokens: kotlin.Int
)

