/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param hate 
 * @param hateThreatening 
 * @param selfHarm 
 * @param sexual 
 * @param sexualMinors 
 * @param violence 
 * @param violenceGraphic 
 */

data class CreateModerationResponseCategoryScores (
    @Json(name = "hate")
    val hate: java.math.BigDecimal,
    @Json(name = "hate/threatening")
    val hateThreatening: java.math.BigDecimal,
    @Json(name = "self-harm")
    val selfHarm: java.math.BigDecimal,
    @Json(name = "sexual")
    val sexual: java.math.BigDecimal,
    @Json(name = "sexual/minors")
    val sexualMinors: java.math.BigDecimal,
    @Json(name = "violence")
    val violence: java.math.BigDecimal,
    @Json(name = "violence/graphic")
    val violenceGraphic: java.math.BigDecimal
)

