/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param model ID of the model to use. You can use the `text-davinci-edit-001` or `code-davinci-edit-001` model with this endpoint.
 * @param instruction The instruction that tells the model how to edit the prompt.
 * @param input The input text to use as a starting point for the edit.
 * @param n How many edits to generate for the input and instruction.
 * @param temperature completions_temperature_description
 * @param topP completions_top_p_description
 */

data class CreateEditRequest (
    /* ID of the model to use. You can use the `text-davinci-edit-001` or `code-davinci-edit-001` model with this endpoint. */
    @Json(name = "model")
    val model: kotlin.String,
    /* The instruction that tells the model how to edit the prompt. */
    @Json(name = "instruction")
    val instruction: kotlin.String,
    /* The input text to use as a starting point for the edit. */
    @Json(name = "input")
    val input: kotlin.String? = null,
    /* How many edits to generate for the input and instruction. */
    @Json(name = "n")
    val n: kotlin.Int? = null,
    /* completions_temperature_description */
    @Json(name = "temperature")
    val temperature: java.math.BigDecimal? = null,
    /* completions_top_p_description */
    @Json(name = "top_p")
    val topP: java.math.BigDecimal? = null
)

