/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.CreateChatCompletionResponseChoices
import org.openapitools.client.models.CreateCompletionResponseUsage

import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param `object` 
 * @param created 
 * @param model 
 * @param choices 
 * @param usage 
 */

data class CreateChatCompletionResponse (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "object")
    val `object`: kotlin.String,
    @Json(name = "created")
    val created: kotlin.Int,
    @Json(name = "model")
    val model: kotlin.String,
    @Json(name = "choices")
    val choices: kotlin.collections.List<CreateChatCompletionResponseChoices>,
    @Json(name = "usage")
    val usage: CreateCompletionResponseUsage? = null
)

