/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param `object` 
 * @param createdAt 
 * @param level 
 * @param message 
 */

data class FineTuneEvent (
    @Json(name = "object")
    val `object`: kotlin.String,
    @Json(name = "created_at")
    val createdAt: kotlin.Int,
    @Json(name = "level")
    val level: kotlin.String,
    @Json(name = "message")
    val message: kotlin.String
)

