/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models

import org.openapitools.client.models.ImagesResponseData

import com.squareup.moshi.Json

/**
 * 
 * @param created 
 * @param data 
 */

data class ImagesResponse (
    @Json(name = "created")
    val created: kotlin.Int,
    @Json(name = "data")
    val data: kotlin.collections.List<ImagesResponseData>
)

