/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param url 
 * @param b64Json 
 */

data class ImagesResponseData (
    @Json(name = "url")
    val url: kotlin.String? = null,
    @Json(name = "b64_json")
    val b64Json: kotlin.String? = null
)

