/**
* OpenAI API
* APIs for sampling from and fine-tuning language models
*
* The version of the OpenAPI document: 1.2.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package org.openapitools.client.models


import com.squareup.moshi.Json

/**
 * 
 * @param id 
 * @param `object` 
 * @param bytes 
 * @param createdAt 
 * @param filename 
 * @param purpose 
 * @param status 
 * @param statusDetails 
 */

data class OpenAIFile (
    @Json(name = "id")
    val id: kotlin.String,
    @Json(name = "object")
    val `object`: kotlin.String,
    @Json(name = "bytes")
    val bytes: kotlin.Int,
    @Json(name = "created_at")
    val createdAt: kotlin.Int,
    @Json(name = "filename")
    val filename: kotlin.String,
    @Json(name = "purpose")
    val purpose: kotlin.String,
    @Json(name = "status")
    val status: kotlin.String? = null,
    @Json(name = "status_details")
    val statusDetails: kotlin.Any? = null
)

